### ISSUE TITLE
如果我想二次转发，我应该配置哪里？

### ISSUE THREAD

**Issue by IAmKongHai** [KenyonY/openai-forward#101]
### Checklist

- [X] 我相信这个想法很棒并且将使框架变得更好
- [X] 我已在issue中搜索了类似请求，包括已关闭的请求

### 详细描述

如果我不想直连 https://api.openai.com ，比如我想链接到 api.openai-forward.com 二次转发，我应该修改哪里？好像要改的地方很多，我都改 ，但是没生效

**Comment by IAmKongHai** [comment]
希望能改成有一个统一配置的地方

**Comment by KenyonY** [comment]
直接修改环境变量或.env文件中
`OPENAI_BASE_URL=https://api.openai-forward.com` 就可以。

**Comment by IAmKongHai** [comment]
> 直接修改环境变量或.env文件中 `OPENAI_BASE_URL=https://api.openai-forward.com` 就可以。

我已经修改了，不行。
我还在 settings.py 里面找到：第 26行：
OPENAI_BASE_URL = env2list("OPENAI_BASE_URL", sep=ENV_VAR_SEP) or [
    "https://api.openai.com"
]
我把这个也改了试试

**Comment by IAmKongHai** [comment]
Error 1101 Ray ID: 8389dc9e2f141668 • 2023-12-20 18:13:52 UTC
Worker threw exception
What happened?
You've requested a page on a website (openai.wndbac.cn) that is on the [Cloudflare](https://www.cloudflare.com/5xx-error-landing/) network. An unknown error occurred while rendering the page.

What can I do?
If you are the owner of this website:
you should [login to Cloudflare](https://www.cloudflare.com/login?utm_source=error_100x) and check the error logs for openai.wndbac.cn.

**Comment by IAmKongHai** [comment]
二次转发的地址改成这个可以了：https://api.openai-forward.com
