### ISSUE TITLE
 429 Too Many Requests 

### ISSUE THREAD

**Issue by ZeguanXiao** [KenyonY/openai-forward#113]
### 初始检查

- [X] 我运行的`openai-forward`版本不低于v0.7.0

### 问题描述

即使没有程序在使用openai api，程序log仍然出现大量的 429 Too Many Requests 。
<img width="749" alt="截屏2024-02-01 13 53 05" src="https://github.com/KenyonY/openai-forward/assets/38279341/07ced484-98e0-4d71-9357-d94095c17486">

### 配置/代码示例和输出

LOG_CHAT=false
  
CACHE_CHAT_COMPLETION=false

CACHE_BACKEND=LevelDB

OPENAI_BASE_URL='https://api.openai.com/v1'
OPENAI_ROUTE_PREFIX='/v1'

CHAT_COMPLETION_ROUTE=/chat/completions
COMPLETION_ROUTE=/completions

EXTRA_BASE_URL='http://chatgpt:7999'
EXTRA_ROUTE_PREFIX='/'

#OPENAI_API_KEY=
#FORWARD_KEY=

#`PROXY` http代理
PROXY=http://localhost:6292
PROXY=http://[占位符]@localhost:6292

#TCP connection timeout duration (in seconds)
TIMEOUT=120

#Set timezone
TZ=Asia/Shanghai

### 环境

python: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
OS: Linux
openai_forward: 0.7.1

### 最后一步

- [X] 我认为上述的描述已经足够详细，开发者能够复现该问题

**Comment by KenyonY** [comment]
Hi @ZeguanXiao 
看到你使用的配置仍然是旧版的，那已经过时了，建议参考最新.env文件更新相关配置。
