### ISSUE TITLE
现在cf  render vercel 部署后访问都是404 

### ISSUE THREAD

**Issue by candies404** [KenyonY/openai-forward#117]
### 初始检查

- [X] 我运行的`openai-forward`版本不低于v0.7.0

### 问题描述

代码已同步至当前版本

### 环境

云平台无法使用该命令

### 最后一步

- [X] 我认为上述的描述已经足够详细，开发者能够复现该问题

**Comment by KenyonY** [comment]
目前只建议使用render部署，其它都已过时。
