### ISSUE TITLE
根据Forward key限制模型访问未生效

### ISSUE THREAD

**Issue by imClumsyPanda** [KenyonY/openai-forward#123]
### 初始检查

- [X] 我运行的`openai-forward`版本不低于v0.7.0

### 问题描述

在.env中设置forward_key对应层级后未正常生效，受限层级用户仍能访问到全部模型。

### 配置/代码示例和输出

FORWARD_CONFIG=[{"base_url": "http://111.11.111.11:8888";, "route": "/", "type": "general"}, {"base_url": "http://111.11.111.12:8888";, "route": "/xxx", "type": "general"}] 
OPENAI_API_KEY={"KEY": [0], "EMPTY": [1]} FORWARD_KEY={"KEY": 0, "EMPTY": 1} 
LEVEL_MODELS={"1": ["Code-Llama-7B-Instruct"]} 
CACHE_OPENAI=False 
CACHE_GENERAL=False 
CACHE_BACKEND=MEMORY 
CACHE_ROOT_PATH_OR_URL=. 
DEFAULT_REQUEST_CACHING_VALUE=False 
CACHE_ROUTES=["/v1/chat/completions"] 
GLOBAL_RATE_LIMIT=inf 
RATE_LIMIT_STRATEGY=fixed-window 
TOKEN_RATE_LIMIT={"/v1/chat/completions": "60/second", "/v1/completions": "60/second"} 
REQ_RATE_LIMIT={"/v1/chat/completions": "100/2minutes", "/v1/completions": "60/minute", "/v1/embeddings": "100/2minutes"} 
ITER_CHUNK_TYPE=efficiency 
LOG_GENERAL=True 
LOG_OPENAI=False 
TZ=Asia/Shanghai 
TIMEOUT=10 
BENCHMARK_MODE=False

### 我的见解

需要确认上述.env中写法是否正确
需要确认多路由转发时api key层级限制是否生效
需要确认api key层级限制对转发类型api是否生效

### 环境

- 操作系统: CentOS 7.4
- Python 版本: 3.8
- OpenAI-Forward 版本: 0.7.1

### 最后一步

- [X] 我认为上述的描述已经足够详细，开发者能够复现该问题

**Comment by KenyonY** [comment]
注意到了你的配置中的转发type都是'general'，当前版本中只支持type为'openai'时 api key的level限制才生效。

**Comment by KenyonY** [comment]
现在general模式下，level也可生效。
