### ISSUE TITLE
Render部署失败

### ISSUE THREAD

**Issue by Autunomy** [KenyonY/openai-forward#124]
### Initial Checks

- [X] My `openai-forward` version is not lower than v0.7.0

### Issue Description

使用render一键部署不成功，请问是我自己的账号原因还是什么问题呢？
![image](https://github.com/KenyonY/openai-forward/assets/73972467/e5d889f3-0953-4659-8f95-340309812cc5)
![image](https://github.com/KenyonY/openai-forward/assets/73972467/321705f7-84c4-419b-816f-a564cf09fba9)

### Environment

使用的是render部署

### Final Step

- [ ] I believe my description above is detailed enough for developers to reproduce the issue.

**Comment by weisong82** [comment]
已经咨询过了， 这种项目不允许部署。

There are certain repositories that we do not permit to be deployed to Render as they are in breach of one or more of the items in our Acceptable Use Policy: https://render.com/acceptable-use.
 
The repo you are trying to deploy is likely on that list and will not be permitted.
