### ISSUE TITLE
没办法实现流式

### ISSUE THREAD

**Issue by zgqq** [KenyonY/openai-forward#128]
### 初始检查

- [X] 我运行的`openai-forward`版本不低于v0.7.0

### 问题描述

![image](https://github.com/KenyonY/openai-forward/assets/10823483/80d16f5b-465a-47e4-9788-2259fce48c31)
现在看起来是等接口全部响应后，再流式过来，期待跟原来接口一样，有响应就立刻转发过来

### 配置/代码示例和输出

LOG_GENERAL=true
LOG_OPENAI=true
FORWARD_CONFIG=[{"base_url":"https://dashscope.aliyuncs.com/compatible-mode/v1","route":"/tongyi","type":"openai"},{"base_url":"https://generativelanguage.googleapis.com","route":"/gemini","type":"general"}]

### 环境

root@7f0ff79e5fb1:/home/openai-forward# python -c "import sys,platform; print('python: {}\nOS: {}'.format(sys.version, platform.system()));"
python: 3.10.14 (main, Apr 10 2024, 04:55:18) [GCC 12.2.0]
OS: Linux
root@7f0ff79e5fb1:/home/openai-forward# python -c "import openai_forward; print('openai_forward: {}'.format(openai_forward.__version__));"
openai_forward: 0.7.2
root@7f0ff79e5fb1:/home/openai-forward#

### 最后一步

- [X] 我认为上述的描述已经足够详细，开发者能够复现该问题

**Comment by KenyonY** [comment]
hi @zgqq ,
这个bug目前在分支 https://github.com/KenyonY/openai-forward/tree/dev-v0.8.0 中已得到修复，可以尝试拉取该分支并使用`pip install -e .` 进行安装后使用。  
也可以直接修改源码：
https://github.com/KenyonY/openai-forward/blob/51257089ea77c2eed540a89e4d5e00287e04b950/openai_forward/forward/core.py#L615 
让`stream=True` 即可
