### ISSUE TITLE
webui 无法保存设置

### ISSUE THREAD

**Issue by jhqwyz** [KenyonY/openai-forward#134]
### 初始检查

- [X] 我运行的`openai-forward`版本不低于v0.7.0

### 问题描述

webui 无法保存设置
添加相关level设置后，点击save键正常
但是点击 Apply and restart 后，一切恢复默认设置

### 配置/代码示例和输出

FORWARD_CONFIG=[{"base_url": "https://api.openai.com", "route": "/", "type": "openai"}]
OPENAI_API_KEY={"": [0]}
FORWARD_KEY={"": 0.0, "fk-MeZyVCaEQIFa01CaEDlQT2BlbkFJKwPWFr3ZRDMfP9ftDhvw": 1.0}
LEVEL_MODELS={"1": ["gpt-3.5-turbo", "gpt-4o"]}
CACHE_OPENAI=False
CACHE_GENERAL=False
CACHE_BACKEND=MEMORY
CACHE_ROOT_PATH_OR_URL=.
DEFAULT_REQUEST_CACHING_VALUE=False
CACHE_ROUTES=["/v1/chat/completions"]
GLOBAL_RATE_LIMIT=inf
RATE_LIMIT_STRATEGY=fixed-window
TOKEN_RATE_LIMIT={"/v1/chat/completions": [{"level": "0", "rate_limit": "60/second"}, {"level": "1", "rate_limit": "3000/second"}], "/v1/completions": [{"level": "0", "rate_limit": "60/second"}, {"level": "1", "rate_limit": "3000/second"}]}
REQ_RATE_LIMIT={"/v1/chat/completions": [{"level": "0", "rate_limit": "100/2minutes"}, {"level": "1", "rate_limit": "2000/2minutes"}], "/v1/completions": [{"level": "0", "rate_limit": "100/2minutes"}, {"level": "1", "rate_limit": "2000/2minutes"}], "/v1/embeddings": [{"level": "0", "rate_limit": "100/2minutes"}, {"level": "1", "rate_limit": "2000/2minutes"}]}
ITER_CHUNK_TYPE=efficiency
LOG_GENERAL=False
LOG_OPENAI=False
TZ=Asia/Shanghai
TIMEOUT=10.0
BENCHMARK_MODE=False
WEBUI_RESTART_PORT=15555
WEBUI_LOG_PORT=15556
DEFAULT_STREAM_RESPONSE=True

### 环境

python: 3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0]
OS: Linux
openai_forward: 0.8.0

### 最后一步

- [X] 我认为上述的描述已经足够详细，开发者能够复现该问题

**Comment by KenyonY** [comment]
可以升级到v0.8.1 看问题是否已得到解决
