### ISSUE TITLE
我想请问提供的地址可以直接使用吗？

### ISSUE THREAD

**Issue by shenxiaochenn** [KenyonY/openai-forward#138]
### Checklist

- [X] 我相信这个想法很棒并且将使框架变得更好
- [X] 我愿提交PR来实现这个想法

### 详细描述

"https://api.openai-forward.com/v1" 我发现您提供的中转接口可以直接使用。。不知道这样有什么风险吗？？

**Comment by KenyonY** [comment]
`https://api.openai-forward.com/` 服务提供个人学习和研究目的使用，勿用于任何商业用途；服务只做转发和速率限制。
