### ISSUE TITLE
如何将最终接口设置成https？

### ISSUE THREAD

**Issue by ape6239** [KenyonY/openai-forward#81]
### Checklist

- [X] 我相信这个想法很棒并且将使框架变得更好
- [X] 我已在issue中搜索了类似请求，包括已关闭的请求

### 详细描述

如题，部分安卓app，不允许http访问，只能用https

**Comment by KenyonY** [comment]
1. 更建议的方式是申请一个域名，然后可以[参考这里](https://github.com/KenyonY/openai-forward/blob/main/deploy.md#%E5%BC%80%E5%90%AFssl-%E4%BB%A5https%E8%AE%BF%E9%97%AE%E5%9F%9F%E5%90%8D) 使用nginx或caddy 和证书 将8000端口转发到https端口。   

2. 但是也可以参考
https://github.com/KenyonY/openai-forward/blob/e7da8de4a48611b84430ca3ea44d355578134b85/openai_forward/__main__.py#L25-L26 
直接通过环境变量传入证书文件路径，让8000端口通过https访问（不推荐）
