### ISSUE TITLE
期待融合accessToken转Token服务

### ISSUE THREAD

**Issue by topkof** [KenyonY/openai-forward#82]
### Checklist

- [X] 我相信这个想法很棒并且将使框架变得更好
- [X] 我已在issue中搜索了类似请求，包括已关闭的请求

### 详细描述

融合accessToken转Token服务就完美了！

**Comment by KenyonY** [comment]
如果这里说的是chatgpt网页中的accessToken，它应该可以结合 [pandora](https://github.com/zhile-io/pandora) 这个项目去实现

**Comment by KenyonY** [comment]
@topkof 
目前自定义秘钥的原始api-key不必以sk-开头，所以对于https://chat.openai.com/api/auth/session 中的accessToken也是可以进行自定义秘钥的
