### ISSUE TITLE
Assistants API support

### ISSUE THREAD

**Issue by KenyonY** [KenyonY/openai-forward#91]
### Detailed Description

ref: https://platform.openai.com/docs/api-reference/assistants  

```bash
curl "https://api.openai.com/v1/assistants" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -H "OpenAI-Beta: assistants=v1" \
  -d '{
    "instructions": "You are a personal math tutor. When asked a question, write and run Python code to answer the question.",
    "name": "Math Tutor",
    "tools": [{"type": "code_interpreter"}],
    "model": "gpt-4"
  }'

```

**Comment by wsdo** [comment]
所以 这个加上了吗？

BadRequestError: Error code: 400 - {'error': {'message': "You must provide the 'OpenAI-Beta' header to access the Assistants API. Please try again by setting the header 'OpenAI-Beta: assistants=v1'.", 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_beta'}}

**Comment by wsdo** [comment]
有没有群，可以直接反馈交流

**Comment by KenyonY** [comment]
@wsdo 已经合并进main分支了，可以试试看
