### ISSUE TITLE
希望增加一个可以禁用模型的选项，因为gpt4太贵，某些场合不想被用户调用。

### ISSUE THREAD

**Issue by wsdo** [KenyonY/openai-forward#94]
### Checklist

- [X] 我相信这个想法很棒并且将使框架变得更好
- [X] 我已在issue中搜索了类似请求，包括已关闭的请求

### 详细描述

希望增加一个可以禁用模型的选项，因为gpt4太贵，某些场合不想被用户调用。

**Comment by KenyonY** [comment]
这个选项也许将来会考虑与forward_key结合起来，为不同的forward_key分配不同的权限；但实现日期无法确定 ¯\_(ツ)_/¯  

如果你希望现在就实现一个简易版本的禁用选项，可以在这里：
https://github.com/KenyonY/openai-forward/blob/4d26d6da6dac5666be69d87f6c26bb8ec012f6f5/openai_forward/forward/base.py#L471-L473
接在这后面，添加对model名称的判断，大概这样：
```python
if valid_payload:
    if payload_info['model'].startwith("gpt-4"):
         raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"model_not_found",
            )
```
