### ISSUE TITLE
accessToken 转 Token 使用疑问

### ISSUE THREAD

**Issue by OrangeCatSleepless** [KenyonY/openai-forward#96]
https://github.com/KenyonY/openai-forward/issues/82#issuecomment-1794170060 中提到可以使用 https://chat.openai.com/api/auth/session 中的 accessToken

对此进行了测试，如果 openai 本身额度已过期的话调用会失败，我尝试使用额度已过期的账号和有额度的账号分别获取 accessToken 来测试，没额度的会报 “502” 或 “You exceeded your current quota, please check your plan and billing details.”，有额度的可以正常使用但会消耗额度，我不确定是否是一个 bug 还是本身就是这样 预期为使用 accessToken 应该无关 openai 是否有额度

**Comment by KenyonY** [comment]
这应该不是bug，使用access token作为api jey的特性是openai的官方接口就支持的，使用的确实是api的额度。
