### ISSUE TITLE
Feat: Azure OpenAI support

### ISSUE THREAD

**Issue by invisprints** [KenyonY/openai-forward#98]
### Checklist

- [X] 我相信这个想法很棒并且将使框架变得更好
- [X] 我已在issue中搜索了类似请求，包括已关闭的请求

### 详细描述

I hope to increase support for Azure OpenAI, so that it can be a simple implementation of CloudFlare AI Gateway!

**Comment by KenyonY** [comment]
因为我没有用过Azure OpenAI，所以一直没考虑过支持Azure OpenAI。后续有可能会支持更多的服务提供方（这块儿更期待有人来贡献）  
CloudFlare AI Gateway提供了很不错的dashboard页面，我也有做个页面的打算，也许会在将来某天实现。

**Comment by KenyonY** [comment]
就目前而言，如果想直接使用本项目代理Azure OpenAI，可以考虑本地启动`openai-forward` 对CloudFlare AI Gateway的相关endpoint进行转发。
